# Generated by Django 4.2 on 2023-11-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ipaddress_alter_posts_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='views',
        ),
        migrations.AddField(
            model_name='posts',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='hits', to='core.ipaddress'),
        ),
    ]
