# Generated by Django 4.2 on 2023-11-16 21:01

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_posts_views_posts_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='caption',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
